### PR TITLE
add `make_dummy_vars` argument

### LINKED ISSUE #6: Look into smds for categorical variables
We saw some unexpected (to me) behavior in the smd for ticket season when using the seven dwarfs data from the touringplans package in the most recent workshop (a single smd vs one for each category) — maybe this is standard from the smd package?

### PR DESCRIPTION
**Pull request by malcolmbarrett**
Closes #6 

@LucyMcGowan, what do you think? Do regression-style dummy variables make sense, or should there be a dummy variable for every level? e.g. `education1` is not included here because it's the comparison/base level

``` r
library(tidysmd)

plot_df <- tidy_smd(
  nhefs_weights,
  c(age, race, education),
  .group = qsmk,
  .wts = w_ate
)

love_plot(plot_df)
```

``` r

plot_df_dummies <- tidy_smd(
  nhefs_weights,
  c(age, race, education),
  .group = qsmk,
  .wts = w_ate,
  dummy_variable = TRUE
)

love_plot(plot_df_dummies)
```

<sup>Created on 2022-08-12 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

### CODE REVIEW

**Comment by LucyMcGowan** [comment]
This looks awesome. I am trying to think about the argument name since it is likely to update multiple variables? So something like `make_dummy` or just `dummy`? (Maybe this is silly!)

**Comment by LucyMcGowan** [comment]
Patrick laughed out loud at `make_dummy` so maybe not 🙃

**Comment by malcolmbarrett** [comment]
Haha maybe ‘make_dummy_vars’. I like a verb here because the original name sort of sounds like it should be the names of dummy variables. 

To confirm, you’re okay with these contrasts? E.g. that there’s no education1 (as there wouldn’t be in regression)?

**Comment by LucyMcGowan** [comment]
Yes! I think that makes sense. The referent is the same as would be picked from a model?

**Comment by malcolmbarrett** [comment]
Right, it uses `model.matrix()` to create them, as do `lm()` and friends. Likewise, you can change the reference group the same was as in a model:

``` r
library(tidysmd)

# make "graduated high school" the reference group
nhefs_weights$education <- relevel(nhefs_weights$education, ref = "3")
  
plot_df_dummies <- tidy_smd(
  nhefs_weights,
  c(age, race, education),
  .group = qsmk,
  .wts = w_ate,
  make_dummy_vars = TRUE
)

love_plot(plot_df_dummies)
```



<sup>Created on 2022-08-13 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Pull request merged**
